import type {
  AttributeDefinition,
  EvidenceDefinition,
  Family,
  PreparationDefinition,
} from "../domain/models";

type Seed = Omit<
  Family,
  "attributes" | "evidence" | "defects" | "variants" | "preparation"
> & {
  attributeLabels: [string, string, string];
  evidenceLabels: [string, string];
};

const preparation = (base: number): PreparationDefinition[] => [
  {
    kind: "CLEAN",
    label: "Temizle",
    costMinor: Math.max(500, Math.round((base * 0.012) / 100) * 100),
    durationMin: 2,
    conditionGain: 4,
    confidenceGain: 0,
    valueGainBps: 180,
    liquidityGainBps: 250,
    maxUses: 1,
  },
  {
    kind: "TEST",
    label: "Test et",
    costMinor: Math.max(700, Math.round((base * 0.018) / 100) * 100),
    durationMin: 3,
    conditionGain: 0,
    confidenceGain: 0.24,
    valueGainBps: 0,
    liquidityGainBps: 350,
    maxUses: 1,
  },
  {
    kind: "COMPLETE",
    label: "Eksikleri tamamla",
    costMinor: Math.max(900, Math.round((base * 0.026) / 100) * 100),
    durationMin: 4,
    conditionGain: 1,
    confidenceGain: 0.06,
    valueGainBps: 300,
    liquidityGainBps: 500,
    maxUses: 1,
  },
];

const attribute = (label: string, index: number): AttributeDefinition => ({
  id: `attribute-${index}`,
  label,
  type: index === 1 ? "NUMBER" : index === 2 ? "BOOLEAN" : "CATEGORY",
  min: index === 1 ? 1 : undefined,
  max: index === 1 ? 100 : undefined,
  step: index === 1 ? 1 : undefined,
  options: index === 0 ? ["Temel", "Plus", "Pro"] : undefined,
  comparePriority: index + 1,
});

const evidence = (label: string, index: number): EvidenceDefinition => ({
  id: `evidence-${index}`,
  label,
  claim: `${label} satıcı beyanı`,
  checkedCopy: `${label} kontrol edildi`,
  inspectionKinds:
    index === 0 ? ["PHOTO", "ASK_SELLER"] : ["ASK_SELLER", "QUICK_TEST"],
  critical: index === 1,
});

const defineFamily = (seed: Seed): Family => {
  const evidenceDefinitions = seed.evidenceLabels.map(evidence);
  return {
    ...seed,
    attributes: seed.attributeLabels.map(attribute),
    evidence: evidenceDefinitions,
    defects: evidenceDefinitions.map((item, index) => ({
      id: `defect-${index}`,
      label: `${item.label} sorunu`,
      severity: index === 1 ? "HIGH" : "MEDIUM",
      valuePenaltyBps: index === 1 ? 1_600 : 800,
      riskSignal: index === 1 ? 0.7 : 0.4,
      evidenceId: item.id,
      overlayKey: index === 1 ? "warning" : "wear",
    })),
    variants: [
      { id: "standard", label: "Standart", valueFactorBps: 10_000 },
      { id: "premium", label: "Üst Paket", valueFactorBps: 11_500 },
    ],
    preparation: preparation(seed.baseValueMinor),
  };
};

const seeds: Seed[] = [
  [
    "notebook",
    "Koleksiyon Kutu Defteri",
    "prd_notebook",
    18_000,
    "Küçük Eşya",
    ["Kapak", "Sayfa", "Orijinallik"],
    ["Kapak izi", "Eksik sayfa"],
  ],
  [
    "vinyl",
    "Koleksiyonluk Klasik Plak Kapsülü",
    "prd_vinyl",
    42_000,
    "Küçük Eşya",
    ["Baskı", "Plak yüzeyi", "Kapak"],
    ["Çizik", "Baskı kodu"],
  ],
  [
    "book",
    "Koleksiyonluk İlk Baskı Seti",
    "prd_book",
    98_000,
    "Küçük Eşya",
    ["Baskı", "Cilt", "İmza"],
    ["Cilt durumu", "İmza doğruluğu"],
  ],
  [
    "sneaker",
    "Koleksiyonlu Kanvas Sneaker",
    "prd_sneaker",
    240_000,
    "Küçük Eşya",
    ["Seri", "Taban", "Kutu"],
    ["Taban aşınması", "Orijinallik"],
  ],
  [
    "headset",
    "Koleksiyon Mini Kulaklık",
    "prd_headset",
    64_000,
    "Ses",
    ["Model", "Pil", "Mikrofon"],
    ["Kozmetik durum", "Ses testi"],
  ],
  [
    "speaker",
    "Koleksiyon Hoparlör Figürü",
    "prd_speaker",
    185_000,
    "Ses",
    ["Sürücü", "Güç", "Kablo"],
    ["Kabin durumu", "Sürücü testi"],
  ],
  [
    "turntable",
    "Koleksiyon Pikap Kiti",
    "prd_turntable",
    280_000,
    "Ses",
    ["İğne", "Devir", "Kapak"],
    ["İğne görünümü", "Devir testi"],
  ],
  [
    "record_player",
    "Koleksiyon Plak Çalar",
    "prd_record_player",
    175_000,
    "Ses",
    ["İğne", "Hoparlör", "Kasa"],
    ["Kasa durumu", "Motor testi"],
  ],
  [
    "desk",
    "Koleksiyon Mini Masa",
    "prd_desk",
    360_000,
    "Ev/Yaşam",
    ["Malzeme", "Genişlik", "Çekmece"],
    ["Yüzey durumu", "Taşıyıcı kontrolü"],
  ],
  [
    "chair",
    "Koleksiyon Sandalye",
    "prd_chair",
    76_000,
    "Ev/Yaşam",
    ["Kumaş", "Yükseklik", "Kolçak"],
    ["Leke", "İskelet kontrolü"],
  ],
  [
    "coffee",
    "Koleksiyon Espresso Ekipmanı",
    "prd_coffee",
    690_000,
    "Ev/Yaşam",
    ["Model", "Basınç", "Aksesuar"],
    ["Kireç izi", "Pompa testi"],
  ],
  [
    "lamp",
    "Koleksiyon Masa Lambası",
    "prd_lamp",
    52_000,
    "Ev/Yaşam",
    ["Gövde", "Güç", "Ampul"],
    ["Kablo durumu", "Elektrik testi"],
  ],
  [
    "console",
    "Koleksiyon Oyun Konsolu",
    "prd_console",
    1_600_000,
    "Oyun",
    ["Sürüm", "Depolama", "Kontrolcü"],
    ["Kasa görünümü", "Çalışma testi"],
  ],
  [
    "handheld",
    "Koleksiyon Taşınabilir Konsol",
    "prd_handheld",
    1_050_000,
    "Oyun",
    ["Sürüm", "Pil", "Şarj cihazı"],
    ["Ekran durumu", "Tuş testi"],
  ],
  [
    "controller",
    "Koleksiyon Kumanda Seti",
    "prd_controller",
    320_000,
    "Oyun",
    ["Model", "Pil", "Kablo"],
    ["Kasa görünümü", "Analog testi"],
  ],
  [
    "game_collection",
    "Koleksiyon Oyuncak Figür Seti",
    "prd_game_collection",
    150_000,
    "Oyun",
    ["Set Türü", "Adet", "Kutulu"],
    ["Figür durumu", "İşçilik kontrolü"],
  ],
  [
    "guitar",
    "Koleksiyon Gitar Figürü",
    "prd_guitar",
    1_200_000,
    "Müzik",
    ["Gövde", "Perde", "Kılıf"],
    ["Gövde izi", "Elektronik testi"],
  ],
  [
    "keyboard",
    "Koleksiyon Klavye Seti",
    "prd_keyboard",
    420_000,
    "Müzik",
    ["Model", "Tuş sayısı", "Adaptör"],
    ["Tuş görünümü", "Ses testi"],
  ],
  [
    "microphone",
    "Koleksiyon Mikrofon Figürü",
    "prd_microphone",
    260_000,
    "Müzik",
    ["Kapsül", "Bağlantı", "Stand"],
    ["Gövde izi", "Kayıt testi"],
  ],
  [
    "pedal",
    "Koleksiyon Efekt Pedalı",
    "prd_pedal",
    190_000,
    "Müzik",
    ["Seri", "Potans", "Kutu"],
    ["Kasa izi", "Sinyal testi"],
  ],
  [
    "phone",
    "Koleksiyon Mini Telefon",
    "prd_phone",
    820_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kutu"],
    ["Ekran durumu", "Cihaz testi"],
  ],
  [
    "compact_phone",
    "Koleksiyon Cep Telefonu",
    "prd_compact_phone",
    540_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Şarj cihazı"],
    ["Kasa durumu", "Şebeke testi"],
  ],
  [
    "tablet",
    "Koleksiyon Tablet Seri",
    "prd_tablet",
    760_000,
    "Telefon",
    ["Model", "Depolama", "Kalem"],
    ["Ekran durumu", "Dokunmatik testi"],
  ],
  [
    "smartwatch",
    "Koleksiyon Akıllı Saat",
    "prd_smartwatch",
    310_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kordon"],
    ["Ekran durumu", "Sensör testi"],
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.58 + (index % 5) * 0.06,
    liquidity: 0.55 + (index % 4) * 0.08,
    category: category as string,
    tier: Math.max(
      Math.min(3, Math.floor(index / 8)),
      Number(baseValueMinor) >= 1_000_000 ? 2 : 0,
    ),
    rarity: 1 + (index % 3),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const scaledSeeds: Seed[] = [
  [
    "mechanical_watch",
    "Koleksiyon Mekanik Saat",
    "prd_watch",
    460_000,
    "Küçük Eşya",
    ["Mekanizma", "Kasa", "Kordon"],
    ["Kasa izi", "Mekanizma testi"],
    1,
  ],
  [
    "fountain_pen",
    "Koleksiyon Kalem Seti",
    "prd_fountain_pen",
    125_000,
    "Küçük Eşya",
    ["Uç", "Gövde", "Kutu"],
    ["Gövde izi", "Mürekkep testi"],
    0,
  ],
  [
    "board_game",
    "Premium Koleksiyon Masa Oyunu",
    "prd_board_game",
    84_000,
    "Küçük Eşya",
    ["Baskı", "Parça sayısı", "Kutu"],
    ["Kutu durumu", "Parça kontrolü"],
    0,
  ],
  [
    "vintage_lighter",
    "Koleksiyon Cep Ateşlemeli",
    "prd_vintage_lighter",
    155_000,
    "Küçük Eşya",
    ["Seri", "Gövde", "Kapak"],
    ["Gövde izi", "Ateşleme testi"],
    1,
  ],
  [
    "portable_radio",
    "Koleksiyon Cep Radyosu",
    "prd_portable_radio",
    115_000,
    "Ses",
    ["Bant", "Anten", "Pil yuvası"],
    ["Kasa durumu", "Frekans testi"],
    0,
  ],
  [
    "studio_monitor",
    "Koleksiyon Stüdyo Hoparlör Seti",
    "prd_studio_monitor",
    640_000,
    "Ses",
    ["Sürücü", "Güç", "Çift"],
    ["Kabin durumu", "Frekans testi"],
    2,
  ],
  [
    "dac_amp",
    "Koleksiyon Ses Arayüzü",
    "prd_dac_amp",
    370_000,
    "Ses",
    ["Çip", "Giriş", "Adaptör"],
    ["Kasa izi", "Çıkış testi"],
    1,
  ],
  [
    "cassette_player",
    "Koleksiyon Kaset Çaları",
    "prd_cassette_player",
    220_000,
    "Ses",
    ["Mekanizma", "Kulaklık çıkışı", "Kapak"],
    ["Kapak durumu", "Devir testi"],
    1,
  ],
  [
    "floor_lamp",
    "Koleksiyon Zemin Lambası",
    "prd_floor_lamp",
    185_000,
    "Ev/Yaşam",
    ["Gövde", "Yükseklik", "Başlık"],
    ["Yüzey durumu", "Elektrik testi"],
    0,
  ],
  [
    "side_table",
    "Koleksiyon Yan Sehpa",
    "prd_side_table",
    245_000,
    "Ev/Yaşam",
    ["Malzeme", "Çap", "Ayak"],
    ["Yüzey durumu", "Denge testi"],
    1,
  ],
  [
    "robot_vacuum",
    "Koleksiyon Robot Süpürge",
    "prd_robot_vacuum",
    780_000,
    "Ev/Yaşam",
    ["Model", "Pil", "İstasyon"],
    ["Kasa durumu", "Sensör testi"],
    2,
  ],
  [
    "stand_mixer",
    "Koleksiyon Mini Mutfak Mikseri",
    "prd_stand_mixer",
    520_000,
    "Ev/Yaşam",
    ["Güç", "Hazne", "Aparat"],
    ["Gövde izi", "Motor testi"],
    2,
  ],
  [
    "vr_headset",
    "Koleksiyon VR Seti",
    "prd_vr_headset",
    1_400_000,
    "Oyun",
    ["Sürüm", "Lens", "Kontrolcü"],
    ["Lens durumu", "Takip testi"],
    2,
  ],
  [
    "gaming_keyboard",
    "Koleksiyon Oyun Klavyesi",
    "prd_gaming_keyboard",
    230_000,
    "Oyun",
    ["Switch", "Dizilim", "Kablo"],
    ["Tuş görünümü", "Tuş testi"],
    1,
  ],
  [
    "racing_wheel",
    "Koleksiyon Yarış Direksiyonu",
    "prd_racing_wheel",
    1_200_000,
    "Oyun",
    ["Model", "Pedal", "Adaptör"],
    ["Gövde durumu", "Eksen testi"],
    2,
  ],
  [
    "game_cartridge",
    "Nadir Koleksiyon Kartuşu",
    "prd_game_cartridge",
    175_000,
    "Oyun",
    ["Bölge", "Etiket", "Kutu"],
    ["Etiket durumu", "Çalışma testi"],
    0,
  ],
  [
    "bass_guitar",
    "Koleksiyon Bas Gitar",
    "prd_bass_guitar",
    680_000,
    "Müzik",
    ["Gövde", "Perde", "Kılıf"],
    ["Gövde izi", "Elektronik testi"],
    2,
  ],
  [
    "audio_interface",
    "Koleksiyon Ses Arayüzü",
    "prd_audio_interface",
    340_000,
    "Müzik",
    ["Giriş", "Bağlantı", "Kutu"],
    ["Kasa izi", "Kayıt testi"],
    1,
  ],
  [
    "drum_machine",
    "Koleksiyon Davul Seti",
    "prd_drum_machine",
    460_000,
    "Müzik",
    ["Sürüm", "Pad", "Adaptör"],
    ["Panel durumu", "Çıkış testi"],
    2,
  ],
  [
    "violin",
    "Koleksiyon Keman Figürü",
    "prd_violin",
    295_000,
    "Müzik",
    ["Gövde", "Yay", "Kutu"],
    ["Gövde izi", "Akort testi"],
    1,
  ],
  [
    "fold_phone",
    "Koleksiyon Katlanır Telefon",
    "prd_fold_phone",
    2_800_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Menteşe"],
    ["Ekran durumu", "Menteşe testi"],
    3,
  ],
  [
    "rugged_phone",
    "Koleksiyon Dayanıklı Telefon",
    "prd_rugged_phone",
    690_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kapak"],
    ["Kasa durumu", "Şebeke testi"],
    2,
  ],
  [
    "e_reader",
    "Koleksiyon E-Kitap",
    "prd_e_reader",
    410_000,
    "Telefon",
    ["Model", "Depolama", "Kılıf"],
    ["Ekran durumu", "Dokunmatik testi"],
    1,
  ],
  [
    "mobile_projector",
    "Koleksiyon Mini Projeksiyon",
    "prd_mobile_projector",
    610_000,
    "Telefon",
    ["Model", "Parlaklık", "Adaptör"],
    ["Lens durumu", "Görüntü testi"],
    2,
  ],
  [
    "laptop",
    "Koleksiyon Mini Dizüstü",
    "prd_laptop",
    1_850_000,
    "Bilgisayar",
    ["İşlemci", "Pil sağlığı", "Adaptör"],
    ["Kasa durumu", "Sistem testi"],
    3,
  ],
  [
    "monitor",
    "Koleksiyon Monitör",
    "prd_monitor",
    720_000,
    "Bilgisayar",
    ["Boyut", "Panel", "Stand"],
    ["Panel durumu", "Piksel testi"],
    2,
  ],
  [
    "mini_pc",
    "Koleksiyon Mini PC",
    "prd_mini_pc",
    980_000,
    "Bilgisayar",
    ["İşlemci", "Depolama", "Adaptör"],
    ["Kasa durumu", "Sistem testi"],
    2,
  ],
  [
    "mechanical_keyboard",
    "Koleksiyon Mekanik Klavye",
    "prd_mechanical_keyboard",
    280_000,
    "Bilgisayar",
    ["Switch", "Dizilim", "Kablo"],
    ["Tuş görünümü", "Tuş testi"],
    1,
  ],
  [
    "graphics_tablet",
    "Koleksiyon Çizim Tableti",
    "prd_graphics_tablet",
    390_000,
    "Bilgisayar",
    ["Alan", "Basınç", "Kalem"],
    ["Yüzey durumu", "Basınç testi"],
    1,
  ],
  [
    "router",
    "Koleksiyon Ağ Gücü",
    "prd_router",
    330_000,
    "Bilgisayar",
    ["Sürüm", "Port", "Adaptör"],
    ["Kasa durumu", "Bağlantı testi"],
    1,
  ],
  [
    "camera",
    "Koleksiyon Kamera",
    "prd_camera",
    3_000_000,
    "Fotoğraf",
    ["Sensör", "Perde sayısı", "Kutu"],
    ["Gövde durumu", "Sensör testi"],
    3,
  ],
  [
    "camera_lens",
    "Koleksiyon Portre Lens",
    "prd_camera_lens",
    1_400_000,
    "Fotoğraf",
    ["Odak", "Diyafram", "Kapak"],
    ["Cam durumu", "Netleme testi"],
    2,
  ],
  [
    "instant_camera",
    "Koleksiyon Anlık Kamera",
    "prd_instant_camera",
    360_000,
    "Fotoğraf",
    ["Model", "Flaş", "Kayış"],
    ["Gövde durumu", "Film testi"],
    1,
  ],
  [
    "tripod",
    "Koleksiyon Tripod",
    "prd_tripod",
    270_000,
    "Fotoğraf",
    ["Malzeme", "Yükseklik", "Başlık"],
    ["Gövde izi", "Kilit testi"],
    1,
  ],
  [
    "camera_flash",
    "Koleksiyon Stüdyo Flaş",
    "prd_camera_flash",
    310_000,
    "Fotoğraf",
    ["Güç", "Başlık", "Kılıf"],
    ["Gövde durumu", "Tetik testi"],
    1,
  ],
  [
    "action_camera",
    "Koleksiyon Aksiyon Kamera",
    "prd_action_camera",
    540_000,
    "Fotoğraf",
    ["Sürüm", "Pil", "Kafes"],
    ["Lens durumu", "Kayıt testi"],
    2,
  ],
  [
    "perfume_set",
    "Koleksiyon Aromatik Set",
    "prd_perfume_set",
    210_000,
    "Moda/Bakım",
    ["Koku grubu", "Doluluk", "Kutu"],
    ["Şişe durumu", "Püskürtme testi"],
    1,
  ],
  [
    "makeup_set",
    "Koleksiyon Makyaj Kiti",
    "prd_makeup_set",
    68_000,
    "Moda/Bakım",
    ["Palet türü", "Parça sayısı", "Mühür"],
    ["Mühür durumu", "İçerik kontrolü"],
    0,
  ],
  [
    "trench_coat",
    "Koleksiyon Trençkot",
    "prd_trench_coat",
    125_000,
    "Moda/Bakım",
    ["Kumaş", "Beden", "Kemer"],
    ["Leke kontrolü", "Dikiş kontrolü"],
    0,
  ],
  [
    "leather_bag",
    "Koleksiyon Deri Çanta",
    "prd_leather_bag",
    275_000,
    "Moda/Bakım",
    ["Malzeme", "Bölme", "Toz torbası"],
    ["Köşe aşınması", "Fermuar testi"],
    1,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.56 + (index % 5) * 0.065,
    liquidity: 0.54 + (index % 4) * 0.075,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 3),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

export const heroFamilies: Family[] = seeds.map(defineFamily);
export const families: Family[] = [
  ...heroFamilies,
  ...scaledSeeds.map(defineFamily),
];
export const familyById = (id: string) =>
  families.find((family) => family.id === id);
