import type {
  AttributeDefinition,
  EvidenceDefinition,
  Family,
  PreparationDefinition,
} from "../domain/models";

type Seed = Omit<
  Family,
  "attributes" | "evidence" | "defects" | "variants" | "preparation"
> & {
  attributeLabels: [string, string, string];
  evidenceLabels: [string, string];
};

const preparation = (base: number): PreparationDefinition[] => [
  {
    kind: "CLEAN",
    label: "Temizle",
    costMinor: Math.max(500, Math.round((base * 0.012) / 100) * 100),
    durationMin: 2,
    conditionGain: 4,
    confidenceGain: 0,
    valueGainBps: 180,
    liquidityGainBps: 250,
    maxUses: 1,
  },
  {
    kind: "TEST",
    label: "Test et",
    costMinor: Math.max(700, Math.round((base * 0.018) / 100) * 100),
    durationMin: 3,
    conditionGain: 0,
    confidenceGain: 0.24,
    valueGainBps: 0,
    liquidityGainBps: 350,
    maxUses: 1,
  },
  {
    kind: "COMPLETE",
    label: "Eksikleri tamamla",
    costMinor: Math.max(900, Math.round((base * 0.026) / 100) * 100),
    durationMin: 4,
    conditionGain: 1,
    confidenceGain: 0.06,
    valueGainBps: 300,
    liquidityGainBps: 500,
    maxUses: 1,
  },
];

const attribute = (label: string, index: number): AttributeDefinition => ({
  id: `attribute-${index}`,
  label,
  type: index === 1 ? "NUMBER" : index === 2 ? "BOOLEAN" : "CATEGORY",
  min: index === 1 ? 1 : undefined,
  max: index === 1 ? 100 : undefined,
  step: index === 1 ? 1 : undefined,
  options: index === 0 ? ["Temel", "Plus", "Pro"] : undefined,
  comparePriority: index + 1,
});

const evidence = (label: string, index: number): EvidenceDefinition => ({
  id: `evidence-${index}`,
  label,
  claim: `${label} satıcı beyanı`,
  checkedCopy: `${label} kontrol edildi`,
  inspectionKinds:
    index === 0 ? ["PHOTO", "ASK_SELLER"] : ["ASK_SELLER", "QUICK_TEST"],
  critical: index === 1,
});

const defineFamily = (seed: Seed): Family => {
  const evidenceDefinitions = seed.evidenceLabels.map(evidence);
  return {
    ...seed,
    attributes: seed.attributeLabels.map(attribute),
    evidence: evidenceDefinitions,
    defects: evidenceDefinitions.map((item, index) => ({
      id: `defect-${index}`,
      label: `${item.label} sorunu`,
      severity: index === 1 ? "HIGH" : "MEDIUM",
      valuePenaltyBps: index === 1 ? 1_600 : 800,
      riskSignal: index === 1 ? 0.7 : 0.4,
      evidenceId: item.id,
      overlayKey: index === 1 ? "warning" : "wear",
    })),
    variants: [
      { id: "standard", label: "Standart", valueFactorBps: 10_000 },
      { id: "premium", label: "Üst Paket", valueFactorBps: 11_500 },
    ],
    preparation: preparation(seed.baseValueMinor),
  };
};

const seeds: Seed[] = [
  [
    "notebook",
    "Deri Kapaklı Kutu Defteri",
    "prd_notebook",
    18_000,
    "Küçük Eşya",
    ["Kapak", "Sayfa", "Orijinallik"],
    ["Kapak izi", "Eksik sayfa"],
  ],
  [
    "vinyl",
    "Koleksiyonluk Klasik Plak",
    "prd_vinyl",
    42_000,
    "Küçük Eşya",
    ["Baskı", "Plak yüzeyi", "Kapak"],
    ["Çizik", "Baskı kodu"],
  ],
  [
    "book",
    "Koleksiyonluk İlk Baskı Kitap Seti",
    "prd_book",
    98_000,
    "Küçük Eşya",
    ["Baskı", "Cilt", "İmza"],
    ["Cilt durumu", "İmza doğruluğu"],
  ],
  [
    "sneaker",
    "Kanvas Günlük Sneaker",
    "prd_sneaker",
    240_000,
    "Küçük Eşya",
    ["Seri", "Taban", "Kutu"],
    ["Taban aşınması", "Orijinallik"],
  ],
  [
    "headset",
    "Kablosuz Kulak Üstü Kulaklık",
    "prd_headset",
    64_000,
    "Ses",
    ["Model", "Pil", "Mikrofon"],
    ["Kozmetik durum", "Ses testi"],
  ],
  [
    "speaker",
    "Raf Tipi Hoparlör",
    "prd_speaker",
    185_000,
    "Ses",
    ["Sürücü", "Güç", "Kablo"],
    ["Kabin durumu", "Sürücü testi"],
  ],
  [
    "turntable",
    "Klasik Pikap",
    "prd_turntable",
    280_000,
    "Ses",
    ["İğne", "Devir", "Kapak"],
    ["İğne görünümü", "Devir testi"],
  ],
  [
    "record_player",
    "Dahili Hoparlörlü Plak Çalar",
    "prd_record_player",
    175_000,
    "Ses",
    ["İğne", "Hoparlör", "Kasa"],
    ["Kasa durumu", "Motor testi"],
  ],
  [
    "desk",
    "Kompakt Çalışma Masası",
    "prd_desk",
    360_000,
    "Ev/Yaşam",
    ["Malzeme", "Genişlik", "Çekmece"],
    ["Yüzey durumu", "Taşıyıcı kontrolü"],
  ],
  [
    "chair",
    "Kumaş Çalışma Sandalyesi",
    "prd_chair",
    76_000,
    "Ev/Yaşam",
    ["Kumaş", "Yükseklik", "Kolçak"],
    ["Leke", "İskelet kontrolü"],
  ],
  [
    "coffee",
    "Ev Tipi Espresso Makinesi",
    "prd_coffee",
    690_000,
    "Ev/Yaşam",
    ["Model", "Basınç", "Aksesuar"],
    ["Kireç izi", "Pompa testi"],
  ],
  [
    "lamp",
    "Metal Gövdeli Masa Lambası",
    "prd_lamp",
    52_000,
    "Ev/Yaşam",
    ["Gövde", "Güç", "Ampul"],
    ["Kablo durumu", "Elektrik testi"],
  ],
  [
    "console",
    "Ev Tipi Oyun Konsolu",
    "prd_console",
    1_600_000,
    "Oyun",
    ["Sürüm", "Depolama", "Kontrolcü"],
    ["Kasa görünümü", "Çalışma testi"],
  ],
  [
    "handheld",
    "Taşınabilir Oyun Konsolu",
    "prd_handheld",
    1_050_000,
    "Oyun",
    ["Sürüm", "Pil", "Şarj cihazı"],
    ["Ekran durumu", "Tuş testi"],
  ],
  [
    "controller",
    "Kablosuz Kumanda Seti",
    "prd_controller",
    320_000,
    "Oyun",
    ["Model", "Pil", "Kablo"],
    ["Kasa görünümü", "Analog testi"],
  ],
  [
    "game_collection",
    "Koleksiyonluk Oyuncak Figür Seti",
    "prd_game_collection",
    150_000,
    "Oyun",
    ["Set Türü", "Adet", "Kutulu"],
    ["Figür durumu", "İşçilik kontrolü"],
  ],
  [
    "guitar",
    "Elektro Gitar",
    "prd_guitar",
    1_200_000,
    "Müzik",
    ["Gövde", "Perde", "Kılıf"],
    ["Gövde izi", "Elektronik testi"],
  ],
  [
    "keyboard",
    "Elektronik Klavye",
    "prd_keyboard",
    420_000,
    "Müzik",
    ["Model", "Tuş sayısı", "Adaptör"],
    ["Tuş görünümü", "Ses testi"],
  ],
  [
    "microphone",
    "Stüdyo Mikrofonu",
    "prd_microphone",
    260_000,
    "Müzik",
    ["Kapsül", "Bağlantı", "Stand"],
    ["Gövde izi", "Kayıt testi"],
  ],
  [
    "pedal",
    "Analog Efekt Pedalı",
    "prd_pedal",
    190_000,
    "Müzik",
    ["Seri", "Potans", "Kutu"],
    ["Kasa izi", "Sinyal testi"],
  ],
  [
    "phone",
    "Akıllı Telefon",
    "prd_phone",
    820_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kutu"],
    ["Ekran durumu", "Cihaz testi"],
  ],
  [
    "compact_phone",
    "Kompakt Cep Telefonu",
    "prd_compact_phone",
    540_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Şarj cihazı"],
    ["Kasa durumu", "Şebeke testi"],
  ],
  [
    "tablet",
    "Kalem Destekli Tablet",
    "prd_tablet",
    760_000,
    "Telefon",
    ["Model", "Depolama", "Kalem"],
    ["Ekran durumu", "Dokunmatik testi"],
  ],
  [
    "smartwatch",
    "Akıllı Saat",
    "prd_smartwatch",
    310_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kordon"],
    ["Ekran durumu", "Sensör testi"],
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.58 + (index % 5) * 0.06,
    liquidity: 0.55 + (index % 4) * 0.08,
    category: category as string,
    tier: Math.max(
      Math.min(3, Math.floor(index / 8)),
      Number(baseValueMinor) >= 1_000_000 ? 2 : 0,
    ),
    rarity: 1 + (index % 3),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const scaledSeeds: Seed[] = [
  [
    "mechanical_watch",
    "Koleksiyonluk Mekanik Saat",
    "prd_watch",
    460_000,
    "Küçük Eşya",
    ["Mekanizma", "Kasa", "Kordon"],
    ["Kasa izi", "Mekanizma testi"],
    1,
  ],
  [
    "fountain_pen",
    "Koleksiyonluk Dolma Kalem Seti",
    "prd_fountain_pen",
    125_000,
    "Küçük Eşya",
    ["Uç", "Gövde", "Kutu"],
    ["Gövde izi", "Mürekkep testi"],
    0,
  ],
  [
    "board_game",
    "Delüks Masa Oyunu",
    "prd_board_game",
    84_000,
    "Küçük Eşya",
    ["Baskı", "Parça sayısı", "Kutu"],
    ["Kutu durumu", "Parça kontrolü"],
    0,
  ],
  [
    "vintage_lighter",
    "Koleksiyonluk Metal Çakmak",
    "prd_vintage_lighter",
    155_000,
    "Küçük Eşya",
    ["Seri", "Gövde", "Kapak"],
    ["Gövde izi", "Ateşleme testi"],
    1,
  ],
  [
    "portable_radio",
    "Taşınabilir Cep Radyosu",
    "prd_portable_radio",
    115_000,
    "Ses",
    ["Bant", "Anten", "Pil yuvası"],
    ["Kasa durumu", "Frekans testi"],
    0,
  ],
  [
    "studio_monitor",
    "Çift Stüdyo Monitörü",
    "prd_studio_monitor",
    640_000,
    "Ses",
    ["Sürücü", "Güç", "Çift"],
    ["Kabin durumu", "Frekans testi"],
    2,
  ],
  [
    "dac_amp",
    "Masaüstü DAC ve Kulaklık Amfisi",
    "prd_dac_amp",
    370_000,
    "Ses",
    ["Çip", "Giriş", "Adaptör"],
    ["Kasa izi", "Çıkış testi"],
    1,
  ],
  [
    "cassette_player",
    "Taşınabilir Kasetçalar",
    "prd_cassette_player",
    220_000,
    "Ses",
    ["Mekanizma", "Kulaklık çıkışı", "Kapak"],
    ["Kapak durumu", "Devir testi"],
    1,
  ],
  [
    "floor_lamp",
    "Ayarlanabilir Zemin Lambası",
    "prd_floor_lamp",
    185_000,
    "Ev/Yaşam",
    ["Gövde", "Yükseklik", "Başlık"],
    ["Yüzey durumu", "Elektrik testi"],
    0,
  ],
  [
    "side_table",
    "Ahşap Yan Sehpa",
    "prd_side_table",
    245_000,
    "Ev/Yaşam",
    ["Malzeme", "Çap", "Ayak"],
    ["Yüzey durumu", "Denge testi"],
    1,
  ],
  [
    "robot_vacuum",
    "Haritalamalı Robot Süpürge",
    "prd_robot_vacuum",
    780_000,
    "Ev/Yaşam",
    ["Model", "Pil", "İstasyon"],
    ["Kasa durumu", "Sensör testi"],
    2,
  ],
  [
    "stand_mixer",
    "Tezgâh Tipi Mutfak Mikseri",
    "prd_stand_mixer",
    520_000,
    "Ev/Yaşam",
    ["Güç", "Hazne", "Aparat"],
    ["Gövde izi", "Motor testi"],
    2,
  ],
  [
    "vr_headset",
    "Sanal Gerçeklik Seti",
    "prd_vr_headset",
    1_400_000,
    "Oyun",
    ["Sürüm", "Lens", "Kontrolcü"],
    ["Lens durumu", "Takip testi"],
    2,
  ],
  [
    "gaming_keyboard",
    "Mekanik Oyun Klavyesi",
    "prd_gaming_keyboard",
    230_000,
    "Oyun",
    ["Switch", "Dizilim", "Kablo"],
    ["Tuş görünümü", "Tuş testi"],
    1,
  ],
  [
    "racing_wheel",
    "Geri Bildirimli Yarış Direksiyonu",
    "prd_racing_wheel",
    1_200_000,
    "Oyun",
    ["Model", "Pedal", "Adaptör"],
    ["Gövde durumu", "Eksen testi"],
    2,
  ],
  [
    "game_cartridge",
    "Nadir Koleksiyon Oyun Kartuşu",
    "prd_game_cartridge",
    175_000,
    "Oyun",
    ["Bölge", "Etiket", "Kutu"],
    ["Etiket durumu", "Çalışma testi"],
    0,
  ],
  [
    "bass_guitar",
    "Dört Telli Bas Gitar",
    "prd_bass_guitar",
    680_000,
    "Müzik",
    ["Gövde", "Perde", "Kılıf"],
    ["Gövde izi", "Elektronik testi"],
    2,
  ],
  [
    "audio_interface",
    "USB Ses Kayıt Arayüzü",
    "prd_audio_interface",
    340_000,
    "Müzik",
    ["Giriş", "Bağlantı", "Kutu"],
    ["Kasa izi", "Kayıt testi"],
    1,
  ],
  [
    "drum_machine",
    "Programlanabilir Davul Makinesi",
    "prd_drum_machine",
    460_000,
    "Müzik",
    ["Sürüm", "Pad", "Adaptör"],
    ["Panel durumu", "Çıkış testi"],
    2,
  ],
  [
    "violin",
    "Öğrenci Tipi Keman",
    "prd_violin",
    295_000,
    "Müzik",
    ["Gövde", "Yay", "Kutu"],
    ["Gövde izi", "Akort testi"],
    1,
  ],
  [
    "fold_phone",
    "Katlanabilir Akıllı Telefon",
    "prd_fold_phone",
    2_800_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Menteşe"],
    ["Ekran durumu", "Menteşe testi"],
    3,
  ],
  [
    "rugged_phone",
    "Darbeye Dayanıklı Telefon",
    "prd_rugged_phone",
    690_000,
    "Telefon",
    ["Model", "Pil sağlığı", "Kapak"],
    ["Kasa durumu", "Şebeke testi"],
    2,
  ],
  [
    "e_reader",
    "E-Kitap Okuyucu",
    "prd_e_reader",
    410_000,
    "Telefon",
    ["Model", "Depolama", "Kılıf"],
    ["Ekran durumu", "Dokunmatik testi"],
    1,
  ],
  [
    "mobile_projector",
    "Taşınabilir Mini Projektör",
    "prd_mobile_projector",
    610_000,
    "Telefon",
    ["Model", "Parlaklık", "Adaptör"],
    ["Lens durumu", "Görüntü testi"],
    2,
  ],
  [
    "laptop",
    "İnce ve Hafif Dizüstü",
    "prd_laptop",
    1_850_000,
    "Bilgisayar",
    ["İşlemci", "Pil sağlığı", "Adaptör"],
    ["Kasa durumu", "Sistem testi"],
    3,
  ],
  [
    "monitor",
    "Yüksek Yenilemeli Monitör",
    "prd_monitor",
    720_000,
    "Bilgisayar",
    ["Boyut", "Panel", "Stand"],
    ["Panel durumu", "Piksel testi"],
    2,
  ],
  [
    "mini_pc",
    "Kompakt Masaüstü Bilgisayar",
    "prd_mini_pc",
    980_000,
    "Bilgisayar",
    ["İşlemci", "Depolama", "Adaptör"],
    ["Kasa durumu", "Sistem testi"],
    2,
  ],
  [
    "mechanical_keyboard",
    "Mekanik Masaüstü Klavye",
    "prd_mechanical_keyboard",
    280_000,
    "Bilgisayar",
    ["Switch", "Dizilim", "Kablo"],
    ["Tuş görünümü", "Tuş testi"],
    1,
  ],
  [
    "graphics_tablet",
    "Basınç Hassasiyetli Çizim Tableti",
    "prd_graphics_tablet",
    390_000,
    "Bilgisayar",
    ["Alan", "Basınç", "Kalem"],
    ["Yüzey durumu", "Basınç testi"],
    1,
  ],
  [
    "router",
    "Kablosuz Ağ Yönlendirici",
    "prd_router",
    330_000,
    "Bilgisayar",
    ["Sürüm", "Port", "Adaptör"],
    ["Kasa durumu", "Bağlantı testi"],
    1,
  ],
  [
    "camera",
    "Aynasız Dijital Kamera",
    "prd_camera",
    3_000_000,
    "Fotoğraf",
    ["Sensör", "Perde sayısı", "Kutu"],
    ["Gövde durumu", "Sensör testi"],
    3,
  ],
  [
    "camera_lens",
    "Sabit Odaklı Portre Lensi",
    "prd_camera_lens",
    1_400_000,
    "Fotoğraf",
    ["Odak", "Diyafram", "Kapak"],
    ["Cam durumu", "Netleme testi"],
    2,
  ],
  [
    "instant_camera",
    "Anında Baskılı Kamera",
    "prd_instant_camera",
    360_000,
    "Fotoğraf",
    ["Model", "Flaş", "Kayış"],
    ["Gövde durumu", "Film testi"],
    1,
  ],
  [
    "tripod",
    "Alüminyum Kamera Tripodu",
    "prd_tripod",
    270_000,
    "Fotoğraf",
    ["Malzeme", "Yükseklik", "Başlık"],
    ["Gövde izi", "Kilit testi"],
    1,
  ],
  [
    "camera_flash",
    "Taşınabilir Stüdyo Flaşı",
    "prd_camera_flash",
    310_000,
    "Fotoğraf",
    ["Güç", "Başlık", "Kılıf"],
    ["Gövde durumu", "Tetik testi"],
    1,
  ],
  [
    "action_camera",
    "Su Geçirmez Aksiyon Kamerası",
    "prd_action_camera",
    540_000,
    "Fotoğraf",
    ["Sürüm", "Pil", "Kafes"],
    ["Lens durumu", "Kayıt testi"],
    2,
  ],
  [
    "perfume_set",
    "Seçkili Parfüm Seti",
    "prd_perfume_set",
    210_000,
    "Moda/Bakım",
    ["Koku grubu", "Doluluk", "Kutu"],
    ["Şişe durumu", "Püskürtme testi"],
    1,
  ],
  [
    "makeup_set",
    "Profesyonel Makyaj Kiti",
    "prd_makeup_set",
    68_000,
    "Moda/Bakım",
    ["Palet türü", "Parça sayısı", "Mühür"],
    ["Mühür durumu", "İçerik kontrolü"],
    0,
  ],
  [
    "trench_coat",
    "Klasik Kesim Trençkot",
    "prd_trench_coat",
    125_000,
    "Moda/Bakım",
    ["Kumaş", "Beden", "Kemer"],
    ["Leke kontrolü", "Dikiş kontrolü"],
    0,
  ],
  [
    "leather_bag",
    "Hakiki Deri Omuz Çantası",
    "prd_leather_bag",
    275_000,
    "Moda/Bakım",
    ["Malzeme", "Bölme", "Toz torbası"],
    ["Köşe aşınması", "Fermuar testi"],
    1,
  ],
  [
    "cordless_vacuum",
    "Kablosuz Şarjlı Süpürge",
    "prd_cordless_vacuum",
    910_000,
    "Ev/Yaşam",
    ["Pil ömrü", "Süpürme modu", "Dikiş"],
    ["Fırça durumu", "Filtre testi"],
    2,
  ],
  [
    "handheld_vacuum",
    "Kompakt El Süpürgesi",
    "prd_handheld_vacuum",
    370_000,
    "Ev/Yaşam",
    ["Güç", "Şarj süresi", "Nozül"],
    ["Filtre durumu", "Motor testi"],
    1,
  ],
  [
    "stick_vacuum",
    "Hafif Dikey Süpürge",
    "prd_stick_vacuum",
    1_250_000,
    "Ev/Yaşam",
    ["Çekiş", "Pil kapasitesi", "Navigasyon"],
    ["Çıkıntı kaydı", "Dokunmatik test"],
    3,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.56 + (index % 5) * 0.065,
    liquidity: 0.54 + (index % 4) * 0.075,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 3),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const mediumBudgetSeeds: Seed[] = [
  [
    "air_fryer",
    "Dijital Sıcak Hava Fritözü",
    "prd_air_fryer",
    650_000,
    "Ev/Yaşam",
    ["Kapasite", "Güç", "Sepet"],
    ["Gövde durumu", "Isıtma testi"],
    2,
  ],
  [
    "sewing_machine",
    "Taşınabilir Dikiş Makinesi",
    "prd_sewing_machine",
    580_000,
    "Ev/Yaşam",
    ["Dikiş türü", "Pedal", "Aksesuar"],
    ["Gövde durumu", "Motor testi"],
    2,
  ],
  [
    "air_purifier",
    "Akıllı Hava Temizleyici",
    "prd_air_purifier",
    720_000,
    "Ev/Yaşam",
    ["Kapasite", "Filtre", "Kademe"],
    ["Filtre durumu", "Fan testi"],
    2,
  ],
  [
    "cordless_drill",
    "18V Şarjlı Matkap",
    "prd_cordless_drill",
    460_000,
    "Ev/Yaşam",
    ["Voltaj", "Pil", "Mandren"],
    ["Gövde durumu", "Tork testi"],
    1,
  ],
  [
    "headphones",
    "Kablosuz Stüdyo Kulaklığı",
    "prd_headphones",
    480_000,
    "Ses",
    ["Sürücü", "Pil", "Ped"],
    ["Ped durumu", "Ses testi"],
    1,
  ],
  [
    "soundbar",
    "Sinema Ses Çubuğu Seti",
    "prd_soundbar",
    690_000,
    "Ses",
    ["Kanal", "Güç", "Bas ünitesi"],
    ["Kabin durumu", "Bağlantı testi"],
    2,
  ],
  [
    "portable_recorder",
    "Taşınabilir Ses Kayıt Cihazı",
    "prd_portable_recorder",
    560_000,
    "Ses",
    ["Mikrofon", "Giriş", "Depolama"],
    ["Gövde durumu", "Kayıt testi"],
    2,
  ],
  [
    "karaoke_speaker",
    "Kablosuz Karaoke Hoparlörü",
    "prd_karaoke_speaker",
    620_000,
    "Ses",
    ["Güç", "Pil", "Mikrofon"],
    ["Kabin durumu", "Mikrofon testi"],
    2,
  ],
  [
    "webcam",
    "Full HD Görüşme Kamerası",
    "prd_webcam",
    240_000,
    "Bilgisayar",
    ["Çözünürlük", "Mikrofon", "Bağlantı"],
    ["Lens durumu", "Görüntü testi"],
    1,
  ],
  [
    "external_ssd",
    "1 TB Taşınabilir Depolama",
    "prd_external_ssd",
    360_000,
    "Bilgisayar",
    ["Kapasite", "Bağlantı", "Kablo"],
    ["Kasa durumu", "Hız testi"],
    1,
  ],
  [
    "photo_printer",
    "Kompakt Fotoğraf Yazıcısı",
    "prd_photo_printer",
    580_000,
    "Fotoğraf",
    ["Baskı boyutu", "Bağlantı", "Tepsi"],
    ["Gövde durumu", "Baskı testi"],
    2,
  ],
  [
    "mesh_router",
    "Üçlü Ağ İstasyonu Seti",
    "prd_mesh_router",
    480_000,
    "Bilgisayar",
    ["Düğüm sayısı", "Port", "Adaptör"],
    ["Kasa durumu", "Bağlantı testi"],
    1,
  ],
  [
    "arcade_stick",
    "Arcade Kontrolcüsü",
    "prd_arcade_stick",
    450_000,
    "Oyun",
    ["Kol tipi", "Tuş sayısı", "Kablo"],
    ["Panel durumu", "Tuş testi"],
    1,
  ],
  [
    "flight_joystick",
    "Uçuş Simülasyon Kumandası",
    "prd_flight_joystick",
    520_000,
    "Oyun",
    ["Eksen", "Gaz kolu", "Bağlantı"],
    ["Gövde durumu", "Eksen testi"],
    2,
  ],
  [
    "gaming_mouse",
    "Hafif Oyun Faresi",
    "prd_gaming_mouse",
    260_000,
    "Oyun",
    ["Sensör", "Tuş sayısı", "Bağlantı"],
    ["Gövde durumu", "Tuş testi"],
    1,
  ],
  [
    "mini_drone",
    "Katlanabilir Mini Drone",
    "prd_mini_drone",
    950_000,
    "Fotoğraf",
    ["Kamera", "Uçuş süresi", "Kumanda"],
    ["Pervane durumu", "Uçuş testi"],
    2,
  ],
  [
    "camera_gimbal",
    "Üç Eksen Kamera Sabitleyici",
    "prd_camera_gimbal",
    650_000,
    "Fotoğraf",
    ["Eksen", "Taşıma yükü", "Pil"],
    ["Kol durumu", "Denge testi"],
    2,
  ],
  [
    "binoculars",
    "10x42 Arazi Dürbünü",
    "prd_binoculars",
    390_000,
    "Fotoğraf",
    ["Büyütme", "Mercek", "Kılıf"],
    ["Mercek durumu", "Netlik testi"],
    1,
  ],
  [
    "telescope",
    "Başlangıç Teleskop Seti",
    "prd_telescope",
    730_000,
    "Fotoğraf",
    ["Açıklık", "Odak", "Tripod"],
    ["Mercek durumu", "Netlik testi"],
    2,
  ],
  [
    "film_scanner",
    "Masaüstü Film Tarayıcı",
    "prd_film_scanner",
    470_000,
    "Fotoğraf",
    ["Film türü", "Çözünürlük", "Tutucu"],
    ["Gövde durumu", "Tarama testi"],
    1,
  ],
  [
    "ukulele",
    "Maun Ukulele",
    "prd_ukulele",
    290_000,
    "Müzik",
    ["Gövde", "Perde", "Kılıf"],
    ["Gövde durumu", "Akort testi"],
    1,
  ],
  [
    "midi_controller",
    "49 Tuş MIDI Kontrolcüsü",
    "prd_midi_controller",
    450_000,
    "Müzik",
    ["Tuş sayısı", "Pad", "Kablo"],
    ["Tuş durumu", "Bağlantı testi"],
    1,
  ],
  [
    "cajon",
    "Ahşap Kajon",
    "prd_cajon",
    330_000,
    "Müzik",
    ["Gövde", "Tel", "Yüzey"],
    ["Köşe durumu", "Ses testi"],
    1,
  ],
  [
    "harmonica_set",
    "Üçlü Mızıka Seti",
    "prd_harmonica_set",
    180_000,
    "Müzik",
    ["Akort", "Parça sayısı", "Kutu"],
    ["Gövde durumu", "Ses testi"],
    1,
  ],
  [
    "leather_boots",
    "El Yapımı Deri Bot",
    "prd_leather_boots",
    420_000,
    "Moda/Bakım",
    ["Malzeme", "Beden", "Taban"],
    ["Deri durumu", "Taban kontrolü"],
    1,
  ],
  [
    "sunglasses",
    "Polarize Güneş Gözlüğü",
    "prd_sunglasses",
    230_000,
    "Moda/Bakım",
    ["Çerçeve", "Cam", "Kılıf"],
    ["Cam durumu", "Menteşe testi"],
    1,
  ],
  [
    "travel_suitcase",
    "Orta Boy Seyahat Valizi",
    "prd_travel_suitcase",
    550_000,
    "Moda/Bakım",
    ["Boyut", "Gövde", "Teker"],
    ["Köşe durumu", "Kilit testi"],
    2,
  ],
  [
    "leather_wallet",
    "El Yapımı Deri Cüzdan",
    "prd_leather_wallet",
    180_000,
    "Moda/Bakım",
    ["Malzeme", "Bölme", "Kutu"],
    ["Köşe durumu", "Dikiş kontrolü"],
    1,
  ],
  [
    "model_train_set",
    "Elektrikli Model Tren Seti",
    "prd_model_train_set",
    650_000,
    "Oyun",
    ["Ölçek", "Vagon sayısı", "Ray"],
    ["Parça durumu", "Motor testi"],
    2,
  ],
  [
    "diecast_car_set",
    "Altılı Model Araç Seti",
    "prd_diecast_car_set",
    350_000,
    "Oyun",
    ["Ölçek", "Araç sayısı", "Kutu"],
    ["Boya durumu", "Parça kontrolü"],
    1,
  ],
  [
    "building_block_set",
    "Mimari Yapı Blok Seti",
    "prd_building_block_set",
    280_000,
    "Oyun",
    ["Tema", "Parça sayısı", "Kılavuz"],
    ["Parça durumu", "Set kontrolü"],
    1,
  ],
  [
    "rc_car",
    "Arazi Tipi Kumandalı Araç",
    "prd_rc_car",
    420_000,
    "Oyun",
    ["Ölçek", "Pil", "Kumanda"],
    ["Gövde durumu", "Sürüş testi"],
    1,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.59 + (index % 5) * 0.045,
    liquidity: 0.57 + (index % 4) * 0.055,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 3),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const starterExpansionSeeds: Seed[] = [
  [
    "electric_kettle",
    "Isı Ayarlı Su Isıtıcı",
    "prd_electric_kettle",
    95_000,
    "Ev/Yaşam",
    ["Kapasite", "Sıcaklık", "Taban"],
    ["Gövde durumu", "Isıtma testi"],
    1,
  ],
  [
    "blender_set",
    "Çok Parçalı Blender Seti",
    "prd_blender_set",
    180_000,
    "Ev/Yaşam",
    ["Hazne", "Güç", "Aparat"],
    ["Bıçak durumu", "Motor testi"],
    1,
  ],
  [
    "steam_iron",
    "Buharlı Ütü",
    "prd_steam_iron",
    110_000,
    "Ev/Yaşam",
    ["Taban", "Buhar", "Hazne"],
    ["Taban durumu", "Buhar testi"],
    1,
  ],
  [
    "dehumidifier",
    "Kompakt Nem Alma Cihazı",
    "prd_dehumidifier",
    420_000,
    "Ev/Yaşam",
    ["Kapasite", "Kademe", "Hazne"],
    ["Filtre durumu", "Fan testi"],
    2,
  ],
  [
    "bluetooth_speaker",
    "Taşınabilir Bluetooth Hoparlör",
    "prd_bluetooth_speaker",
    140_000,
    "Ses",
    ["Boyut", "Pil", "Bağlantı"],
    ["Gövde durumu", "Ses testi"],
    1,
  ],
  [
    "podcast_microphone",
    "USB Podcast Mikrofonu",
    "prd_podcast_microphone",
    220_000,
    "Ses",
    ["Desen", "Kazanç", "Ayak"],
    ["Izgara durumu", "Kayıt testi"],
    1,
  ],
  [
    "noise_cancel_earbuds",
    "Gürültü Engelleyici Kulak İçi Set",
    "prd_noise_cancel_earbuds",
    260_000,
    "Ses",
    ["Kodek", "Pil", "Kutu"],
    ["Uç durumu", "Ses testi"],
    1,
  ],
  [
    "stereo_receiver",
    "Ev Tipi Stereo Alıcı",
    "prd_stereo_receiver",
    480_000,
    "Ses",
    ["Kanal", "Güç", "Giriş"],
    ["Panel durumu", "Kanal testi"],
    2,
  ],
  [
    "office_keyboard_mouse",
    "Kablosuz Klavye Fare Seti",
    "prd_office_keyboard_mouse",
    95_000,
    "Bilgisayar",
    ["Düzen", "Pil", "Alıcı"],
    ["Tuş durumu", "Bağlantı testi"],
    1,
  ],
  [
    "usb_dock",
    "Çoklu Bağlantı İstasyonu",
    "prd_usb_dock",
    190_000,
    "Bilgisayar",
    ["Port", "Güç", "Kablo"],
    ["Kasa durumu", "Port testi"],
    1,
  ],
  [
    "portable_monitor",
    "Taşınabilir İkinci Ekran",
    "prd_portable_monitor",
    520_000,
    "Bilgisayar",
    ["Panel", "Boyut", "Kılıf"],
    ["Ekran durumu", "Görüntü testi"],
    2,
  ],
  [
    "mini_nas",
    "İki Yuvalı Ev Depolama Ünitesi",
    "prd_mini_nas",
    780_000,
    "Bilgisayar",
    ["Yuva", "Bellek", "Adaptör"],
    ["Yuva durumu", "Ağ testi"],
    2,
  ],
  [
    "ring_light",
    "Ayarlanabilir Halka Işık",
    "prd_ring_light",
    85_000,
    "Fotoğraf",
    ["Çap", "Kademe", "Ayak"],
    ["Gövde durumu", "Işık testi"],
    0,
  ],
  [
    "instant_printer",
    "Cep Tipi Fotoğraf Yazıcısı",
    "prd_instant_printer",
    280_000,
    "Fotoğraf",
    ["Baskı", "Pil", "Kağıt"],
    ["Gövde durumu", "Baskı testi"],
    1,
  ],
  [
    "camera_backpack",
    "Bölmeli Kamera Sırt Çantası",
    "prd_camera_backpack",
    160_000,
    "Fotoğraf",
    ["Hacim", "Bölme", "Yağmurluk"],
    ["Kumaş durumu", "Fermuar testi"],
    1,
  ],
  [
    "light_meter",
    "Dijital Işık Ölçer",
    "prd_light_meter",
    240_000,
    "Fotoğraf",
    ["Ölçüm", "Ekran", "Kılıf"],
    ["Sensör durumu", "Ölçüm testi"],
    1,
  ],
  [
    "wooden_puzzle_set",
    "Ahşap Zeka Oyunu Seti",
    "prd_wooden_puzzle_set",
    65_000,
    "Oyun",
    ["Zorluk", "Parça", "Kutu"],
    ["Parça durumu", "Set kontrolü"],
    0,
  ],
  [
    "tabletop_miniatures",
    "Masaüstü Minyatür Seti",
    "prd_tabletop_miniatures",
    180_000,
    "Oyun",
    ["Seri", "Parça", "Kutu"],
    ["Boya durumu", "Parça kontrolü"],
    1,
  ],
  [
    "dance_mat",
    "Kablosuz Dans Platformu",
    "prd_dance_mat",
    150_000,
    "Oyun",
    ["Yüzey", "Bağlantı", "Sensör"],
    ["Yüzey durumu", "Tuş testi"],
    1,
  ],
  [
    "capture_card",
    "Oyun Görüntü Aktarım Kartı",
    "prd_capture_card",
    240_000,
    "Oyun",
    ["Çözünürlük", "Giriş", "Kablo"],
    ["Kasa durumu", "Aktarım testi"],
    1,
  ],
  [
    "kalimba",
    "17 Tuş Kalimba",
    "prd_kalimba",
    70_000,
    "Müzik",
    ["Gövde", "Tuş", "Kılıf"],
    ["Gövde durumu", "Akort testi"],
    0,
  ],
  [
    "digital_metronome",
    "Dijital Metronom",
    "prd_digital_metronome",
    45_000,
    "Müzik",
    ["Tempo", "Ekran", "Pil"],
    ["Gövde durumu", "Tempo testi"],
    0,
  ],
  [
    "electronic_drum_pad",
    "Elektronik Davul Pedi",
    "prd_electronic_drum_pad",
    360_000,
    "Müzik",
    ["Ped", "Ses", "Pedal"],
    ["Ped durumu", "Vuruş testi"],
    2,
  ],
  [
    "alto_saxophone",
    "Başlangıç Alto Saksafon",
    "prd_alto_saxophone",
    850_000,
    "Müzik",
    ["Gövde", "Tuş", "Çanta"],
    ["Kaplama durumu", "Ses testi"],
    2,
  ],
  [
    "hair_styler",
    "Çok Başlıklı Saç Şekillendirici",
    "prd_hair_styler",
    340_000,
    "Moda/Bakım",
    ["Başlık", "Isı", "Çanta"],
    ["Gövde durumu", "Isıtma testi"],
    2,
  ],
  [
    "leather_jacket",
    "Hakiki Deri Ceket",
    "prd_leather_jacket",
    380_000,
    "Moda/Bakım",
    ["Deri", "Beden", "Astar"],
    ["Yüzey durumu", "Dikiş kontrolü"],
    2,
  ],
  [
    "travel_backpack",
    "Şehir Tipi Seyahat Sırt Çantası",
    "prd_travel_backpack",
    190_000,
    "Moda/Bakım",
    ["Hacim", "Bölme", "Askı"],
    ["Kumaş durumu", "Fermuar testi"],
    1,
  ],
  [
    "skin_care_device",
    "Yüz Bakım Cihazı",
    "prd_skin_care_device",
    230_000,
    "Moda/Bakım",
    ["Başlık", "Kademe", "Şarj"],
    ["Başlık durumu", "Çalışma testi"],
    1,
  ],
  [
    "wooden_chess_set",
    "Ahşap Satranç Takımı",
    "prd_wooden_chess_set",
    120_000,
    "Küçük Eşya",
    ["Ağaç", "Taş", "Kutu"],
    ["Yüzey durumu", "Parça kontrolü"],
    1,
  ],
  [
    "mechanical_desk_clock",
    "Mekanik Masa Saati",
    "prd_mechanical_desk_clock",
    150_000,
    "Küçük Eşya",
    ["Mekanizma", "Kasa", "Cam"],
    ["Kasa durumu", "Zaman testi"],
    1,
  ],
  [
    "precision_tool_set",
    "Hassas Tamir Seti",
    "prd_precision_tool_set",
    75_000,
    "Küçük Eşya",
    ["Uç", "Sap", "Kutu"],
    ["Uç durumu", "Set kontrolü"],
    0,
  ],
  [
    "brass_compass",
    "Pirinç Cep Pusulası",
    "prd_brass_compass",
    90_000,
    "Küçük Eşya",
    ["Gövde", "İbre", "Kapak"],
    ["Yüzey durumu", "Yön testi"],
    0,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.58 + (index % 5) * 0.05,
    liquidity: 0.56 + (index % 4) * 0.06,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 2),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const upperMidSeeds: Seed[] = [
  [
    "air_compressor",
    "50 Litre Hava Kompresörü",
    "prd_air_compressor",
    1_850_000,
    "Ev/Yaşam",
    ["Depo", "Basınç", "Tekerlek"],
    ["Depo durumu", "Basınç testi"],
    3,
  ],
  [
    "thickness_planer",
    "Tezgâh Tipi Kalınlık Planyası",
    "prd_thickness_planer",
    2_450_000,
    "Ev/Yaşam",
    ["Genişlik", "Kademe", "Bıçak"],
    ["Tabla durumu", "Motor testi"],
    3,
  ],
  [
    "inverter_welder",
    "Yüksek Amper İnverter Kaynak",
    "prd_inverter_welder",
    2_200_000,
    "Ev/Yaşam",
    ["Amper", "Kablo", "Çanta"],
    ["Kasa durumu", "Akım testi"],
    3,
  ],
  [
    "motorized_treadmill",
    "Katlanabilir Motorlu Koşu Bandı",
    "prd_motorized_treadmill",
    3_200_000,
    "Ev/Yaşam",
    ["Bant", "Eğim", "Motor"],
    ["Bant durumu", "Motor testi"],
    3,
  ],
  [
    "analog_audio_mixer",
    "12 Kanal Analog Ses Mikseri",
    "prd_analog_audio_mixer",
    2_100_000,
    "Ses",
    ["Kanal", "Efekt", "Adaptör"],
    ["Panel durumu", "Kanal testi"],
    3,
  ],
  [
    "digital_piano",
    "88 Tuş Mobilya Tipi Dijital Piyano",
    "prd_digital_piano",
    4_200_000,
    "Müzik",
    ["Tuş", "Pedal", "Sehpa"],
    ["Tuş durumu", "Ses testi"],
    3,
  ],
  [
    "acoustic_drum_kit",
    "Beş Parça Akustik Davul Seti",
    "prd_acoustic_drum_kit",
    4_800_000,
    "Müzik",
    ["Gövde", "Zil", "Tabure"],
    ["Deri durumu", "Donanım testi"],
    3,
  ],
  [
    "studio_strobe_kit",
    "İki Işıklı Stüdyo Paraflaş Seti",
    "prd_studio_strobe_kit",
    3_550_000,
    "Fotoğraf",
    ["Güç", "Ayak", "Şemsiye"],
    ["Gövde durumu", "Flaş testi"],
    3,
  ],
  [
    "laser_engraver",
    "Masaüstü Lazer Kazıma Makinesi",
    "prd_laser_engraver",
    3_600_000,
    "Bilgisayar",
    ["Alan", "Güç", "Koruma"],
    ["Ray durumu", "Kazıma testi"],
    3,
  ],
  [
    "table_saw",
    "Tezgâh Tipi Daire Testere",
    "prd_table_saw",
    2_800_000,
    "Ev/Yaşam",
    ["Tabla", "Bıçak", "Kılavuz"],
    ["Tabla durumu", "Motor testi"],
    3,
  ],
  [
    "portable_generator",
    "Taşınabilir Sessiz Jeneratör",
    "prd_portable_generator",
    3_000_000,
    "Ev/Yaşam",
    ["Güç", "Depo", "Priz"],
    ["Gövde durumu", "Yük testi"],
    3,
  ],
  [
    "pressure_washer",
    "Yüksek Basınçlı Yıkama Makinesi",
    "prd_pressure_washer",
    2_200_000,
    "Ev/Yaşam",
    ["Basınç", "Hortum", "Başlık"],
    ["Pompa durumu", "Basınç testi"],
    3,
  ],
  [
    "prosumer_espresso",
    "Yarı Profesyonel Espresso Makinesi",
    "prd_prosumer_espresso",
    4_500_000,
    "Ev/Yaşam",
    ["Kazan", "Öğütücü", "Buhar"],
    ["Gövde durumu", "Basınç testi"],
    3,
  ],
  [
    "massage_chair",
    "Tam Boy Masaj Koltuğu",
    "prd_massage_chair",
    5_800_000,
    "Ev/Yaşam",
    ["Program", "Ray", "Kumanda"],
    ["Döşeme durumu", "Mekanizma testi"],
    3,
  ],
  [
    "pottery_wheel",
    "Elektrikli Seramik Çömlek Tornası",
    "prd_pottery_wheel",
    1_900_000,
    "Küçük Eşya",
    ["Tabla", "Pedal", "Hazne"],
    ["Tabla durumu", "Devir testi"],
    3,
  ],
  [
    "vinyl_cutting_plotter",
    "Masaüstü Folyo Kesim Plotteri",
    "prd_vinyl_cutting_plotter",
    2_600_000,
    "Bilgisayar",
    ["Genişlik", "Bıçak", "Bağlantı"],
    ["Ray durumu", "Kesim testi"],
    3,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.49 + (index % 5) * 0.05,
    liquidity: 0.46 + (index % 4) * 0.055,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 2),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

export const heroFamilies: Family[] = seeds.map(defineFamily);
export const mediumBudgetFamilies: Family[] =
  mediumBudgetSeeds.map(defineFamily);
export const starterExpansionFamilies: Family[] =
  starterExpansionSeeds.map(defineFamily);
export const upperMidFamilies: Family[] = upperMidSeeds.map(defineFamily);

type CapitalBridgeProfile = {
  evidenceClaims: [string, string];
  checkedCopy: [string, string];
  defectLabels: [string, string];
  variantLabels: [string, string];
  preparationLabels: [string, string, string];
};

const capitalBridgeProfiles: Record<string, CapitalBridgeProfile> = {
  cinema_camera_kit: {
    evidenceClaims: ["Gövde darbeye maruz kalmadı", "Sensörde leke yok"],
    checkedCopy: [
      "Bağlantılar ve kafes yuvaları görüldü",
      "Sensör kaydı incelendi",
    ],
    defectLabels: ["Kafes yuvası deformasyonu", "Sensör lekesi"],
    variantLabels: ["Gövde Kiti", "Prodüksiyon Kiti"],
    preparationLabels: ["Gövdeyi temizle", "Sensör kaydı al", "Kiti tamamla"],
  },
  workstation_laptop: {
    evidenceClaims: ["Kasada darbe izi yok", "Yük altında kararlı çalışıyor"],
    checkedCopy: ["Kasa ve bağlantılar görüldü", "Isı ve pil testi tamamlandı"],
    defectLabels: ["Kasa veya menteşe hasarı", "Isınma ve pil sorunu"],
    variantLabels: ["İş İstasyonu", "Stüdyo Paketi"],
    preparationLabels: ["Kasayı temizle", "Yük testi yap", "Adaptörü tamamla"],
  },
  digital_mixing_console: {
    evidenceClaims: ["Panel ve faderlar temiz", "Tüm kanallar sinyal alıyor"],
    checkedCopy: ["Panel aşınması görüldü", "Kanallar tek tek denendi"],
    defectLabels: ["Fader ve panel aşınması", "Kanal veya çıkış arızası"],
    variantLabels: ["Konsol", "Sahne Kutulu Paket"],
    preparationLabels: [
      "Paneli temizle",
      "Kanalları test et",
      "Sahne setini tamamla",
    ],
  },
  commercial_espresso_machine: {
    evidenceClaims: ["Gövde ve grup başlıkları temiz", "Kazan basıncı kararlı"],
    checkedCopy: ["Gövde ve contalar görüldü", "Basınç ve buhar testi yapıldı"],
    defectLabels: ["Conta ve gövde yıpranması", "Kazan basınç sorunu"],
    variantLabels: ["Makine", "Servis Hazır Paket"],
    preparationLabels: [
      "Grupları temizle",
      "Basıncı test et",
      "Aksesuarı tamamla",
    ],
  },
  broadcast_lens_set: {
    evidenceClaims: ["Optiklerde çizik ve mantar yok", "Odak halkaları akıcı"],
    checkedCopy: [
      "Cam ve kaplamalar ışıkta görüldü",
      "Odak hareketi test edildi",
    ],
    defectLabels: ["Optik çizik veya mantar", "Odak mekanizması boşluğu"],
    variantLabels: ["Objektif Seti", "Yayın Hazır Set"],
    preparationLabels: [
      "Optikleri temizle",
      "Odağı test et",
      "Çantayı tamamla",
    ],
  },
  synthesizer_workstation: {
    evidenceClaims: ["Panel ve ekran temiz", "Tüm tuşlar tepki veriyor"],
    checkedCopy: ["Panel kontrolleri görüldü", "Tuş ve ses çıkışı denendi"],
    defectLabels: ["Panel ve encoder aşınması", "Tuş veya ses motoru arızası"],
    variantLabels: ["Enstrüman", "Sahne Paketi"],
    preparationLabels: [
      "Paneli temizle",
      "Tuşları test et",
      "Taşıma setini tamamla",
    ],
  },
  premium_arcade_cabinet: {
    evidenceClaims: [
      "Kabinde şişme ve kırık yok",
      "Kontroller gecikmesiz çalışıyor",
    ],
    checkedCopy: ["Kabin köşeleri görüldü", "Ekran ve kontroller denendi"],
    defectLabels: ["Kabin yüzeyi hasarı", "Ekran veya kontrol arızası"],
    variantLabels: ["Arcade Kabini", "Salon Hazır Paket"],
    preparationLabels: [
      "Kabini temizle",
      "Kontrolleri test et",
      "Paneli tamamla",
    ],
  },
  professional_ceramic_kiln: {
    evidenceClaims: ["Haznede çatlak yok", "Isı programı kararlı tamamlanıyor"],
    checkedCopy: ["Hazne ve rezistans görüldü", "Isı döngüsü test edildi"],
    defectLabels: ["Hazne veya rezistans yıpranması", "Isı kontrol arızası"],
    variantLabels: ["Fırın", "Atölye Hazır Paket"],
    preparationLabels: [
      "Hazneyi temizle",
      "Isı döngüsü çalıştır",
      "Raf setini tamamla",
    ],
  },
  compact_cnc_router: {
    evidenceClaims: ["Raylarda boşluk yok", "Mil yük altında düzgün kesiyor"],
    checkedCopy: ["Ray ve tabla hassasiyeti görüldü", "Örnek kesim tamamlandı"],
    defectLabels: ["Ray ve tabla boşluğu", "Mil veya kontrolcü arızası"],
    variantLabels: ["Tezgâh", "Üretim Hazır Paket"],
    preparationLabels: [
      "Tezgâhı temizle",
      "Örnek kesim yap",
      "Kontrol setini tamamla",
    ],
  },
  industrial_embroidery_machine: {
    evidenceClaims: [
      "Gövde ve iğne yatağı temiz",
      "Tüm kafalar düzgün dikiş atıyor",
    ],
    checkedCopy: ["Gövde ve kasnaklar görüldü", "Örnek desen işlendi"],
    defectLabels: [
      "Kasnak ve gövde yıpranması",
      "İğne kafası zamanlama sorunu",
    ],
    variantLabels: ["Makine", "Üretim Hazır Paket"],
    preparationLabels: [
      "Makineyi temizle",
      "Örnek desen işle",
      "Kasnak setini tamamla",
    ],
  },
  concert_pa_system: {
    evidenceClaims: [
      "Kabinlerde darbe ve çatlak yok",
      "Sistem yükte temiz ses veriyor",
    ],
    checkedCopy: ["Kabin ve bağlantılar görüldü", "Tam güç ses testi yapıldı"],
    defectLabels: ["Kabin veya sürücü hasarı", "Güç ünitesi ve çıkış arızası"],
    variantLabels: ["Ses Sistemi", "Turne Hazır Paket"],
    preparationLabels: [
      "Kabinleri temizle",
      "Yük testi yap",
      "Taşıma setini tamamla",
    ],
  },
  server_rack_bundle: {
    evidenceClaims: [
      "Kabin ve raylar düzgün",
      "Donanım hata vermeden açılıyor",
    ],
    checkedCopy: [
      "Kabin, ray ve yuvalar görüldü",
      "Bellek ve disk testi tamamlandı",
    ],
    defectLabels: ["Kabin ve ray deformasyonu", "Donanım veya disk arızası"],
    variantLabels: ["Sunucu Kabini", "Kurulum Hazır Paket"],
    preparationLabels: [
      "Kabini temizle",
      "Donanımı test et",
      "Ray setini tamamla",
    ],
  },
  broadcast_camera_package: {
    evidenceClaims: ["Gövde ve bağlantılar sağlam", "Görüntüde ölü piksel yok"],
    checkedCopy: [
      "Gövde ve tripod yuvaları görüldü",
      "Kayıt ve çıkışlar test edildi",
    ],
    defectLabels: [
      "Gövde veya bağlantı hasarı",
      "Sensör ve görüntü çıkışı arızası",
    ],
    variantLabels: ["Kamera Paketi", "Stüdyo Hazır Paket"],
    preparationLabels: [
      "Gövdeyi temizle",
      "Görüntüyü test et",
      "Tripodu tamamla",
    ],
  },
  event_led_wall: {
    evidenceClaims: [
      "Panellerde darbe yok",
      "Tüm modüller eşit görüntü veriyor",
    ],
    checkedCopy: [
      "Panel kasaları ve kilitler görüldü",
      "Tam ekran görüntü testi yapıldı",
    ],
    defectLabels: ["Panel ve kilit hasarı", "Ölü modül veya kontrolcü arızası"],
    variantLabels: ["LED Ekran", "Etkinlik Hazır Paket"],
    preparationLabels: [
      "Panelleri temizle",
      "Görüntüyü test et",
      "Kasaları tamamla",
    ],
  },
  industrial_3d_printer: {
    evidenceClaims: [
      "Kabin ve hareket sistemi temiz",
      "Uzun baskıyı hatasız tamamlıyor",
    ],
    checkedCopy: [
      "Kabin, ray ve filtre görüldü",
      "Kalibrasyon baskısı tamamlandı",
    ],
    defectLabels: [
      "Kabin ve ray yıpranması",
      "Nozül veya hareket sistemi arızası",
    ],
    variantLabels: ["3D Yazıcı", "Üretim Hazır Paket"],
    preparationLabels: [
      "Kabini temizle",
      "Kalibrasyon baskısı al",
      "Filtre setini tamamla",
    ],
  },
  grand_digital_piano: {
    evidenceClaims: [
      "Gövde ve tuş yüzeyi temiz",
      "Tüm tuş ve pedallar tepki veriyor",
    ],
    checkedCopy: ["Gövde ve kapak görüldü", "Tuş, pedal ve hoparlör denendi"],
    defectLabels: [
      "Gövde ve tuş yüzeyi hasarı",
      "Tuş sensörü veya ses sistemi arızası",
    ],
    variantLabels: ["Dijital Piyano", "Salon Hazır Paket"],
    preparationLabels: [
      "Gövdeyi temizle",
      "Tuşları test et",
      "Pedal setini tamamla",
    ],
  },
};

const capitalBridgeSeeds: Seed[] = [
  [
    "cinema_camera_kit",
    "Profesyonel Sinema Kamera Kiti",
    "prd_cinema_camera_kit",
    18_500_000,
    "Fotoğraf",
    ["Sensör", "Kayıt saati", "Kafes seti"],
    ["Gövde durumu", "Sensör testi"],
    4,
  ],
  [
    "workstation_laptop",
    "Mobil İş İstasyonu Bilgisayarı",
    "prd_workstation_laptop",
    12_800_000,
    "Bilgisayar",
    ["İşlemci", "Bellek", "Adaptör"],
    ["Kasa durumu", "Yük testi"],
    4,
  ],
  [
    "digital_mixing_console",
    "Dijital Sahne Ses Mikseri",
    "prd_digital_mixing_console",
    16_500_000,
    "Ses",
    ["Kanal", "Sahne kutusu", "Kasa"],
    ["Panel durumu", "Kanal testi"],
    4,
  ],
  [
    "commercial_espresso_machine",
    "İki Gruplu Ticari Espresso Makinesi",
    "prd_commercial_espresso_machine",
    19_500_000,
    "Ev/Yaşam",
    ["Kazan", "Grup başlığı", "Aksesuar"],
    ["Gövde durumu", "Basınç testi"],
    4,
  ],
  [
    "broadcast_lens_set",
    "Yayın Tipi Objektif Seti",
    "prd_broadcast_lens_set",
    14_500_000,
    "Fotoğraf",
    ["Odak aralığı", "Bağlantı", "Taşıma çantası"],
    ["Optik durumu", "Odak testi"],
    4,
  ],
  [
    "synthesizer_workstation",
    "Profesyonel Synthesizer İş İstasyonu",
    "prd_synthesizer_workstation",
    17_500_000,
    "Müzik",
    ["Tuş", "Ses motoru", "Taşıma çantası"],
    ["Panel durumu", "Tuş testi"],
    4,
  ],
  [
    "premium_arcade_cabinet",
    "Tam Boy Arcade Kabini",
    "prd_premium_arcade_cabinet",
    15_000_000,
    "Oyun",
    ["Ekran", "Kontrol paneli", "Kabin"],
    ["Kabin durumu", "Kontrol testi"],
    4,
  ],
  [
    "professional_ceramic_kiln",
    "Programlanabilir Seramik Fırını",
    "prd_professional_ceramic_kiln",
    20_500_000,
    "Ev/Yaşam",
    ["Hacim", "Program", "Raf seti"],
    ["Hazne durumu", "Isı testi"],
    4,
  ],
  [
    "compact_cnc_router",
    "Kompakt CNC Freze Tezgâhı",
    "prd_compact_cnc_router",
    28_000_000,
    "Ev/Yaşam",
    ["Çalışma alanı", "Mil gücü", "Kontrolcü"],
    ["Ray durumu", "Kesim testi"],
    5,
  ],
  [
    "industrial_embroidery_machine",
    "Çok İğneli Nakış Makinesi",
    "prd_industrial_embroidery_machine",
    32_000_000,
    "Ev/Yaşam",
    ["İğne sayısı", "Kasnak", "Ayak"],
    ["Gövde durumu", "Dikiş testi"],
    5,
  ],
  [
    "concert_pa_system",
    "Konser Tipi Ses Sistemi",
    "prd_concert_pa_system",
    42_000_000,
    "Ses",
    ["Kabin", "Güç ünitesi", "Taşıma seti"],
    ["Kabin durumu", "Yük testi"],
    5,
  ],
  [
    "server_rack_bundle",
    "Kurumsal Sunucu Kabini Seti",
    "prd_server_rack_bundle",
    56_000_000,
    "Bilgisayar",
    ["İşlemci", "Disk yuvası", "Ray seti"],
    ["Kabin durumu", "Donanım testi"],
    5,
  ],
  [
    "broadcast_camera_package",
    "Stüdyo Yayın Kamera Paketi",
    "prd_broadcast_camera_package",
    46_000_000,
    "Fotoğraf",
    ["Sensör", "Kayıt ünitesi", "Tripod"],
    ["Gövde durumu", "Görüntü testi"],
    5,
  ],
  [
    "event_led_wall",
    "Etkinlik Tipi LED Ekran Seti",
    "prd_event_led_wall",
    52_000_000,
    "Bilgisayar",
    ["Panel", "Kontrolcü", "Taşıma kasası"],
    ["Panel durumu", "Görüntü testi"],
    5,
  ],
  [
    "industrial_3d_printer",
    "Endüstriyel Kabinli 3D Yazıcı",
    "prd_industrial_3d_printer",
    38_000_000,
    "Bilgisayar",
    ["Baskı hacmi", "Nozül", "Filtre"],
    ["Kabin durumu", "Baskı testi"],
    5,
  ],
  [
    "grand_digital_piano",
    "Kuyruklu Dijital Piyano",
    "prd_grand_digital_piano",
    44_000_000,
    "Müzik",
    ["Tuş", "Pedal", "Tabure"],
    ["Gövde durumu", "Ses testi"],
    5,
  ],
].map(
  (
    [
      id,
      name,
      assetKey,
      baseValueMinor,
      category,
      attributeLabels,
      evidenceLabels,
      tier,
    ],
    index,
  ) => ({
    id: id as string,
    name: name as string,
    assetKey: assetKey as string,
    baseValueMinor: baseValueMinor as number,
    demand: 0.5 + (index % 4) * 0.05,
    liquidity: 0.48 + (index % 3) * 0.06,
    category: category as string,
    tier: tier as number,
    rarity: 1 + (index % 2),
    conditionCap: 96,
    attributeLabels: attributeLabels as [string, string, string],
    evidenceLabels: evidenceLabels as [string, string],
  }),
);

const defineCapitalBridgeFamily = (seed: Seed): Family => {
  const family = defineFamily(seed);
  const profile = capitalBridgeProfiles[seed.id];
  if (!profile) return family;

  return {
    ...family,
    evidence: family.evidence.map((item, index) => ({
      ...item,
      claim: profile.evidenceClaims[index],
      checkedCopy: profile.checkedCopy[index],
    })),
    defects: family.defects.map((item, index) => ({
      ...item,
      label: profile.defectLabels[index],
    })),
    variants: family.variants.map((item, index) => ({
      ...item,
      label: profile.variantLabels[index],
    })),
    preparation: family.preparation.map((item, index) => ({
      ...item,
      label: profile.preparationLabels[index],
    })),
  };
};

export const capitalBridgeFamilies: Family[] = capitalBridgeSeeds.map(
  defineCapitalBridgeFamily,
);

type VehicleSeed = {
  id: string;
  name: string;
  assetKey: string;
  baseValueMinor: number;
  demand: number;
  liquidity: number;
  tier: 4 | 5;
  mileageOptions: [string, string, string];
  secondEvidence: string;
};

const defineVehicleFamily = (seed: VehicleSeed): Family => ({
  id: seed.id,
  name: seed.name,
  assetKey: seed.assetKey,
  baseValueMinor: seed.baseValueMinor,
  demand: seed.demand,
  liquidity: seed.liquidity,
  category: "Araç",
  tier: seed.tier,
  rarity: 2,
  conditionCap: 96,
  attributes: [
    {
      id: "mileage",
      label: "Kilometre",
      type: "CATEGORY",
      options: seed.mileageOptions,
      comparePriority: 1,
    },
    {
      id: "trim",
      label: "Donanım",
      type: "CATEGORY",
      options: ["Temel", "Plus", "Pro"],
      comparePriority: 2,
    },
    {
      id: "spare-key",
      label: "Yedek anahtar",
      type: "BOOLEAN",
      comparePriority: 3,
    },
  ],
  evidence: [
    {
      id: "service-record",
      label: "Bakım kaydı",
      claim: "Düzenli bakım yapıldığı beyanı",
      checkedCopy: "Bakım kayıtları kontrol edildi",
      inspectionKinds: ["PHOTO", "ASK_SELLER"],
      critical: false,
    },
    {
      id: "mechanical-check",
      label: seed.secondEvidence,
      claim: `${seed.secondEvidence} sorunsuz beyanı`,
      checkedCopy: `${seed.secondEvidence} yapıldı`,
      inspectionKinds: ["ASK_SELLER", "QUICK_TEST"],
      critical: true,
    },
  ],
  defects: [
    {
      id: "record-mismatch",
      label: "Bakım kaydı tutarsızlığı",
      severity: "MEDIUM",
      valuePenaltyBps: 900,
      riskSignal: 0.5,
      evidenceId: "service-record",
      overlayKey: "wear",
    },
    {
      id: "mechanical-fault",
      label: `${seed.secondEvidence} sorunu`,
      severity: "HIGH",
      valuePenaltyBps: 2_200,
      riskSignal: 0.82,
      evidenceId: "mechanical-check",
      overlayKey: "warning",
    },
  ],
  variants: [
    { id: "standard", label: "Standart Paket", valueFactorBps: 10_000 },
    { id: "premium", label: "Üst Paket", valueFactorBps: 11_500 },
  ],
  preparation: preparation(seed.baseValueMinor),
});

const vehicleSeeds: VehicleSeed[] = [
  {
    id: "urban_motorcycle",
    name: "Şehir Motosikleti",
    assetKey: "prd_urban_motorcycle",
    baseValueMinor: 32_000_000,
    demand: 0.64,
    liquidity: 0.58,
    tier: 4,
    mileageOptions: ["45 bin km üstü", "20–45 bin km", "20 bin km altı"],
    secondEvidence: "Motor testi",
  },
  {
    id: "touring_motorcycle",
    name: "Uzun Yol Motosikleti",
    assetKey: "prd_touring_motorcycle",
    baseValueMinor: 58_000_000,
    demand: 0.52,
    liquidity: 0.45,
    tier: 4,
    mileageOptions: ["60 bin km üstü", "25–60 bin km", "25 bin km altı"],
    secondEvidence: "Motor testi",
  },
  {
    id: "utility_atv",
    name: "Arazi Tipi ATV",
    assetKey: "prd_utility_atv",
    baseValueMinor: 42_000_000,
    demand: 0.48,
    liquidity: 0.4,
    tier: 4,
    mileageOptions: ["Yoğun kullanım", "Orta kullanım", "Düşük kullanım"],
    secondEvidence: "Aktarma testi",
  },
  {
    id: "compact_hatchback",
    name: "Kompakt Şehir Otomobili",
    assetKey: "prd_compact_hatchback",
    baseValueMinor: 115_000_000,
    demand: 0.69,
    liquidity: 0.62,
    tier: 5,
    mileageOptions: ["180 bin km üstü", "90–180 bin km", "90 bin km altı"],
    secondEvidence: "Motor testi",
  },
  {
    id: "executive_sedan",
    name: "Üst Sınıf Sedan",
    assetKey: "prd_executive_sedan",
    baseValueMinor: 185_000_000,
    demand: 0.46,
    liquidity: 0.38,
    tier: 5,
    mileageOptions: ["160 bin km üstü", "80–160 bin km", "80 bin km altı"],
    secondEvidence: "Ekspertiz kaydı",
  },
  {
    id: "cargo_van",
    name: "Kompakt Hafif Ticari",
    assetKey: "prd_cargo_van",
    baseValueMinor: 225_000_000,
    demand: 0.57,
    liquidity: 0.47,
    tier: 5,
    mileageOptions: ["240 bin km üstü", "120–240 bin km", "120 bin km altı"],
    secondEvidence: "Motor testi",
  },
];

export const vehicleFamilies: Family[] = vehicleSeeds.map(defineVehicleFamily);

export const families: Family[] = [
  ...heroFamilies,
  ...scaledSeeds.map(defineFamily),
  ...mediumBudgetFamilies,
  ...starterExpansionFamilies,
  ...upperMidFamilies,
  ...capitalBridgeFamilies,
  ...vehicleFamilies,
];
export const familyById = (id: string) =>
  families.find((family) => family.id === id);
